name: Nuget

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/bassclefstudio/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

    - name: Build solution and generate NuGet package
      run: |  
          cd ./BassClefStudio.NET.Core
          dotnet pack -c Release -o out

    - name: Push packages to GitHub
      run: dotnet nuget push ./BassClefStudio.NET.Core/out/*.nupkg --skip-duplicate --no-symbols true
